version: "3.9"
services:
  web:
    build: ./admin
    ports:
      - 5001:5000
    depends_on:
      - db
    environment:
      FLASK_DEBUG: True
      DB_HOST: db
    volumes:
    - ./admin:/var/www
  fe:
    build: ./portal
    ports:
      - 8080:5173
    volumes:
    - ./portal:/app
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: grupo30